# Context:
# DC_POWER  — DC power generated by inverter in 15-min interval (kW)
# AC_POWER  — AC power output after inversion (kW)
# DAILY_YIELD  — cumulative power generated that day up to that point (kWh)
# TOTAL_YIELD  — total lifetime yield for that inverter (kWh)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Load ----------------------------------------------------------------------
Gen1  = pd.read_csv('Plant_1_Generation_data.csv',     parse_dates=['DATE_TIME'])
Sens1 = pd.read_csv('Plant_1_Weather_Sensor_Data.csv', parse_dates=['DATE_TIME'])

# --- Merge on datetime + plant ID -----------------------------------------------
Plant1_merge = pd.merge(Gen1, Sens1, on=['DATE_TIME', 'PLANT_ID'], how='left')
Plant1_merge = Plant1_merge.drop(columns=['SOURCE_KEY_y'])
Plant1_merge = Plant1_merge.rename(columns={'SOURCE_KEY_x': 'SOURCE_KEY'})


# --- Handle Missing Data --------------------------------------------------------




# --- Filter to daylight hours only ----------------------------------------------
Plant1_day = Plant1_merge[Plant1_merge['DC_POWER'] > 0].copy()
del Plant1_merge

# --- Compute efficiency ratio ----------------------------------------------------
Plant1_day['EFFICIENCY_RATIO'] = Plant1_day['AC_POWER'] / Plant1_day['DC_POWER']

# --- Set time index --------------------------------------------------------------
Plant1_day = Plant1_day.set_index('DATE_TIME').sort_index()

# --- Plot 1: Efficiency per inverter ---------------------------------------------
plt.figure(figsize=(14, 6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='EFFICIENCY_RATIO')
plt.xticks(rotation=90)
plt.title('Efficiency Ratio per Inverter — Plant 1')
plt.xlabel('Source Key (Inverter)')
plt.ylabel('Efficiency Ratio (AC / DC)')
plt.tight_layout()
plt.show()

# --- Plot 2: DC power vs irradiation ----------------------------------------------
plt.figure(figsize=(10, 6))
sns.scatterplot(data=Plant1_day, x='IRRADIATION', y='DC_POWER')
plt.title('DC Power vs Irradiation — Plant 1')
plt.xlabel('Irradiation (W/m²)')
plt.ylabel('DC Power (kW)')
plt.tight_layout()
plt.show()

