# Context:
# DC_POWER  — DC power generated by inverter in 15-min interval (kW)
# AC_POWER  — AC power output after inversion (kW)
# DAILY_YIELD  — cumulative power generated that day up to that point (kWh)
# TOTAL_YIELD  — total lifetime yield for that inverter (kWh)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Load ----------------------------------------------------------------------
Gen1  = pd.read_csv('Plant_1_Generation_data.csv',     parse_dates=['DATE_TIME'])
Sens1 = pd.read_csv('Plant_1_Weather_Sensor_Data.csv', parse_dates=['DATE_TIME'])

# --- Merge on datetime + plant ID -----------------------------------------------
Plant1_merge = pd.merge(Gen1, Sens1, on=['DATE_TIME', 'PLANT_ID'], how='left')
Plant1_merge = Plant1_merge.drop(columns=['SOURCE_KEY_y'])
Plant1_merge = Plant1_merge.rename(columns={'SOURCE_KEY_x': 'SOURCE_KEY'})

# --- Filter to daylight hours only ----------------------------------------------
Plant1_day = Plant1_merge[
    (Plant1_merge['DC_POWER'] > 0) &
    (Plant1_merge['IRRADIATION'] > 0)
].copy()
Plant1_day = Plant1_day[Plant1_day['AC_POWER'] <= Plant1_day['DC_POWER']].copy()
del Plant1_merge

# --- Handle Missing Data --------------------------------------------------------
print('--- Missing Values on Daylight---')
print(Plant1_day.isnull().sum())

# --- Drop Rows where sensors had no reading (NaN) ------------------------------
missing_before = len(Plant1_day)
Plant1_day = Plant1_day.dropna(subset=['IRRADIATION', 
                                       'AMBIENT_TEMPERATURE', 
                                       'MODULE_TEMPERATURE'])
print(f'\nRows Dropped: {missing_before - len(Plant1_day)}')
print(f'Rows Remaining: {len(Plant1_day)}')




#================================================================================================


# --- Feature 1: AC/DC Efficiency Ratio ----------------------------------------------------
Plant1_day['EFFICIENCY_RATIO'] = Plant1_day['AC_POWER'] / Plant1_day['DC_POWER']

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='EFFICIENCY_RATIO')
plt.xticks(rotation=90)
plt.title('AC/DC Efficiency Ratio per Inverter — Plant 1')
plt.xlabel('Inverter')
plt.ylabel('Efficiency Ratio (AC/DC)')
plt.tight_layout()
#plt.show()

# --- Feature 2: Irradiance-Normalized DC Power ---------------------------------------------------
Plant1_day['IRR_NORM_DC'] = Plant1_day['DC_POWER']/Plant1_day['IRRADIATION']

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='IRR_NORM_DC')
plt.xticks(rotation=90)
plt.title('Irradiance-Normalized DC Power per Inverter')
plt.xlabel('Inverter')
plt.ylabel('DC Power / Irradiation (kW / W/m²)')
plt.tight_layout()
#plt.show()

# --- Normalized Power Loss in Temperature Derating --------------------------------------
TEMP_COEFFICIENT = 0.005 #This comes from the fact that power drops ~0.4-0.5% per °C above 25°C (typical for crystalline silicon)

HIGH_IRR_THRESHOLD = Plant1_day['IRRADIATION'].quantile(0.90)

P_RATED = (Plant1_day[Plant1_day['IRRADIATION'] >= HIGH_IRR_THRESHOLD
                     ].groupby('SOURCE_KEY')['DC_POWER'].quantile(0.95))


Plant1_day['P_RATED'] = Plant1_day['SOURCE_KEY'].map(P_RATED)

Plant1_day['EXPECTED_DC'] = Plant1_day['P_RATED'] * (
  1 - TEMP_COEFFICIENT * (Plant1_day['MODULE_TEMPERATURE'] - 25)
  )

Plant1_day['TEMP_DERATING'] = ((Plant1_day['EXPECTED_DC'] - 
                               Plant1_day['DC_POWER']) / Plant1_day['P_RATED']) * 100

# --- Condition derating on irradiation bins to remove weather effect -------------------
Plant1_day['IRR_BIN'] = pd.cut(Plant1_day['IRRADIATION'], bins=10)
Plant1_day['TEMP_DERATING_CONDITIONED'] = Plant1_day.groupby('IRR_BIN')['TEMP_DERATING'].transform(
  lambda x: (x - x.mean()) / x.std())

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='TEMP_DERATING_CONDITIONED')
plt.xticks(rotation=90)
plt.title('Temperature Derating per Inverter (Irradiation-Conditioned)')
plt.xlabel('Inverter')
plt.ylabel('Conditioned Temperature Derating (Z-Score)')
plt.axhline(y=0, color='red', linestyle='--', linewidth=0.8, label='Fleet Mean')
plt.legend()
plt.tight_layout()
#plt.show()


# --- Rolling 1 Hour Average Deviation per Inverter ------------------------------------
Plant1_day = Plant1_day.sort_values(['SOURCE_KEY', 'DATE_TIME'])

Plant1_day['ROLLING_DC_MEAN'] = (
  Plant1_day
  .set_index('DATE_TIME')
  .groupby('SOURCE_KEY')['DC_POWER']
  .transform(lambda x: x.rolling('1h').mean())
  .values
)
Plant1_day['ROLLING_DEVIATION'] = Plant1_day['DC_POWER'] - Plant1_day['ROLLING_DC_MEAN']
Plant1_day = Plant1_day.reset_index()

# --- Full Fleet Overview -----------------

plt.figure(figsize=(12, 6))
for inverter in Plant1_day['SOURCE_KEY'].unique():
    subset = Plant1_day[Plant1_day['SOURCE_KEY'] == inverter]
    plt.plot(subset['DATE_TIME'], subset['ROLLING_DEVIATION'],
             alpha=0.2, linewidth=0.3, color='steelblue')

plt.axhline(y=0, color='red', linestyle='--', linewidth=0.8, label='Zero Deviation')
plt.axhline(y=-2000, color='orange', linestyle='--', linewidth=0.8, label='Warning Threshold (-2000 kW)')
plt.axhline(y=-4000, color='darkred', linestyle='--', linewidth=0.8, label='Critical Threshold (-4000 kW)')
plt.title('Rolling 1-Hour DC Power Deviation — Full Fleet')
plt.xlabel('Date')
plt.ylabel('Deviation from Rolling Mean (kW)')
plt.legend()
plt.tight_layout()

# --- Flagged Inverters ----------------------
plt.figure(figsize=(12, 6))

# Plot bvBOhCH3iADSZry first as background reference
subset = Plant1_day[Plant1_day['SOURCE_KEY'] == 'bvBOhCH3iADSZry']
plt.plot(subset['DATE_TIME'], subset['ROLLING_DEVIATION'],
         alpha=0.15, linewidth=0.3, color='gray', label='bvBOhCH3iADSZry (reference)')

# Plot the other 4 on top with high visibility
foreground = {
    'sjndEbLyjtCKgGv': 'red',
    'iCRJl6heRkivqQ3': 'orange',
    'McdE0feGgRqW7Ca': 'purple',
    'wCURE6d3bPkepu2': 'deeppink'
}

for inverter, color in foreground.items():
    subset = Plant1_day[Plant1_day['SOURCE_KEY'] == inverter]
    plt.plot(subset['DATE_TIME'], subset['ROLLING_DEVIATION'],
             alpha=0.85, linewidth=0.6, color=color, label=inverter)

plt.axhline(y=0, color='black', linestyle='--', linewidth=0.8, label='Zero Deviation')
plt.title('Rolling Deviation — Flagged Inverters Only')
plt.xlabel('Date')
plt.ylabel('Deviation from Rolling Mean (kW)')
plt.legend(loc='upper right', fontsize=7)
plt.tight_layout()
#plt.show()

# --- Rolling Deviation Stats per Inverter ---
rolling_stats = (Plant1_day.groupby('SOURCE_KEY')['ROLLING_DEVIATION']
                 .agg(['mean', 'std', 'min', 'max'])
                 .rename(columns={
                     'mean': 'MEAN_DEV',
                     'std': 'STD_DEV',
                     'min': 'MIN_DEV',
                     'max': 'MAX_DEV'
                 })
                 .sort_values('STD_DEV', ascending=False))

print('=== Rolling Deviation Stats — Sorted by Std (Highest to Lowest) ===')
print(rolling_stats.to_string())

# --- Highlight wCURE6d3bPkepu2 specifically ---
print('\n=== wCURE6d3bPkepu2 Stats ===')
print(rolling_stats.loc['wCURE6d3bPkepu2'])

# --- Fleet average std for comparison ---
print(f'\nFleet Mean Std: {rolling_stats["STD_DEV"].mean():.3f} kW')
print(f'Fleet Max Std:  {rolling_stats["STD_DEV"].max():.3f} kW')
print(f'Fleet Min Std:  {rolling_stats["STD_DEV"].min():.3f} kW')

