# Context:
# DC_POWER  — DC power generated by inverter in 15-min interval (kW)
# AC_POWER  — AC power output after inversion (kW)
# DAILY_YIELD  — cumulative power generated that day up to that point (kWh)
# TOTAL_YIELD  — total lifetime yield for that inverter (kWh)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Load ----------------------------------------------------------------------
Gen1  = pd.read_csv('Plant_1_Generation_data.csv',     parse_dates=['DATE_TIME'])
Sens1 = pd.read_csv('Plant_1_Weather_Sensor_Data.csv', parse_dates=['DATE_TIME'])

# --- Merge on datetime + plant ID -----------------------------------------------
Plant1_merge = pd.merge(Gen1, Sens1, on=['DATE_TIME', 'PLANT_ID'], how='left')
Plant1_merge = Plant1_merge.drop(columns=['SOURCE_KEY_y'])
Plant1_merge = Plant1_merge.rename(columns={'SOURCE_KEY_x': 'SOURCE_KEY'})

# --- Filter to daylight hours only ----------------------------------------------
Plant1_day = Plant1_merge[
    (Plant1_merge['DC_POWER'] > 0) &
    (Plant1_merge['IRRADIATION'] > 0)
].copy()
Plant1_day = Plant1_day[Plant1_day['AC_POWER'] <= Plant1_day['DC_POWER']].copy()
del Plant1_merge

# --- Handle Missing Data --------------------------------------------------------
print('--- Missing Values on Daylight---')
print(Plant1_day.isnull().sum())

# --- Drop Rows where sensors had no reading (NaN) ------------------------------
missing_before = len(Plant1_day)
Plant1_day = Plant1_day.dropna(subset=['IRRADIATION', 
                                       'AMBIENT_TEMPERATURE', 
                                       'MODULE_TEMPERATURE'])
print(f'\nRows Dropped: {missing_before - len(Plant1_day)}')
print(f'Rows Remaining: {len(Plant1_day)}')

# --- Compute efficiency ratio ----------------------------------------------------
Plant1_day['AC_POWER'] = Plant1_day['AC_POWER']
Plant1_day['EFFICIENCY_RATIO'] = Plant1_day['AC_POWER'] / Plant1_day['DC_POWER']

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='EFFICIENCY_RATIO')
plt.xticks(rotation=90)
plt.title('AC/DC Efficiency Ratio per Inverter — Plant 1')
plt.xlabel('Inverter')
plt.ylabel('Efficiency Ratio (AC/DC)')
plt.tight_layout()


# --- Set time index --------------------------------------------------------------
Plant1_day = Plant1_day.sort_values('DATE_TIME')


# --- Irradiance - Normalized DC Power ---------------------------------------------------
Plant1_day['IRR_NORM_DC'] = Plant1_day['DC_POWER']/Plant1_day['IRRADIATION']
plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='IRR_NORM_DC')
plt.xticks(rotation=90)
plt.title('Irradiance-Normalized DC Power per Inverter')
plt.xlabel('Inverter')
plt.ylabel('DC Power / Irradiation (kW / W/m²)')
plt.tight_layout()


# --- Normalized Power Loss in Temperature Derating --------------------------------------
TEMP_COEFFICIENT = 0.005 #This comes from the fact that power drops ~0.4-0.5% per °C above 25°C (typical for crystalline silicon)

HIGH_IRR_THRESHOLD = Plant1_day['IRRADIATION'].quantile(0.90)

P_RATED = Plant1_day[Plant1_day['IRRADIATION'] >= HIGH_IRR_THRESHOLD
                     ].groupby('SOURCE_KEY')['DC_POWER'].quantile(0.95)

Plant1_day['P_RATED'] = Plant1_day['SOURCE_KEY'].map(P_RATED)

Plant1_day['EXPECTED_DC'] = Plant1_day['P_RATED'] * (
  1 - TEMP_COEFFICIENT * (Plant1_day['MODULE_TEMPERATURE'] - 25)
  )

Plant1_day['TEMP_DERATING'] = ((Plant1_day['EXPECTED_DC'] - 
                               Plant1_day['DC_POWER']) / Plant1_day['P_RATED']) * 100

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='TEMP_DERATING')
plt.xticks(rotation=90)
plt.title('Temperature Derating per Inverter')
plt.xlabel('Inverter')
plt.ylabel('Temperature Derating (%)')
plt.tight_layout()
#plt.show()

print(Plant1_day.groupby('SOURCE_KEY')['P_RATED'].mean().sort_values())
