# Context:
# DC_POWER  — DC power generated by inverter in 15-min interval (kW)
# AC_POWER  — AC power output after inversion (kW)
# DAILY_YIELD  — cumulative power generated that day up to that point (kWh)
# TOTAL_YIELD  — total lifetime yield for that inverter (kWh)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Load ----------------------------------------------------------------------
Gen1  = pd.read_csv('Plant_1_Generation_data.csv',     parse_dates=['DATE_TIME'])
Sens1 = pd.read_csv('Plant_1_Weather_Sensor_Data.csv', parse_dates=['DATE_TIME'])

# --- Merge on datetime + plant ID -----------------------------------------------
Plant1_merge = pd.merge(Gen1, Sens1, on=['DATE_TIME', 'PLANT_ID'], how='left')
Plant1_merge = Plant1_merge.drop(columns=['SOURCE_KEY_y'])
Plant1_merge = Plant1_merge.rename(columns={'SOURCE_KEY_x': 'SOURCE_KEY'})

# --- Filter to daylight hours only ----------------------------------------------
Plant1_day = Plant1_merge[
    (Plant1_merge['DC_POWER'] > 0) &
    (Plant1_merge['IRRADIATION'] > 0)
].copy()
Plant1_day = Plant1_day[Plant1_day['AC_POWER'] <= Plant1_day['DC_POWER']].copy()
del Plant1_merge

# --- Handle Missing Data --------------------------------------------------------
print('--- Missing Values on Daylight---')
print(Plant1_day.isnull().sum())

# --- Drop Rows where sensors had no reading (NaN) ------------------------------
missing_before = len(Plant1_day)
Plant1_day = Plant1_day.dropna(subset=['IRRADIATION', 
                                       'AMBIENT_TEMPERATURE', 
                                       'MODULE_TEMPERATURE'])
print(f'\nRows Dropped: {missing_before - len(Plant1_day)}')
print(f'Rows Remaining: {len(Plant1_day)}')




#================================================================================================
print(Plant1_day.columns)

# --- Baseline: Statistical Threshold Method -----------------------------------------------------

#Extracting hour
Plant1_day['HOUR'] = Plant1_day['DATE_TIME'].dt.hour

#Computing Mean and STD per inverter per hour bucket
hourly_stats = (Plant1_day.groupby('SOURCE_CODE', 'HOUR')['EFFICIENCY_RATIO'])