# Context:
# DC_POWER  — DC power generated by inverter in 15-min interval (kW)
# AC_POWER  — AC power output after inversion (kW)
# DAILY_YIELD  — cumulative power generated that day up to that point (kWh)
# TOTAL_YIELD  — total lifetime yield for that inverter (kWh)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Load ----------------------------------------------------------------------
Gen1  = pd.read_csv('Plant_1_Generation_data.csv',     parse_dates=['DATE_TIME'])
Sens1 = pd.read_csv('Plant_1_Weather_Sensor_Data.csv', parse_dates=['DATE_TIME'])

# --- Merge on datetime + plant ID -----------------------------------------------
Plant1_merge = pd.merge(Gen1, Sens1, on=['DATE_TIME', 'PLANT_ID'], how='left')
Plant1_merge = Plant1_merge.drop(columns=['SOURCE_KEY_y'])
Plant1_merge = Plant1_merge.rename(columns={'SOURCE_KEY_x': 'SOURCE_KEY'})

# --- Filter to daylight hours only ----------------------------------------------
Plant1_day = Plant1_merge[
    (Plant1_merge['DC_POWER'] > 0) &
    (Plant1_merge['IRRADIATION'] > 0)
].copy()
del Plant1_merge

# --- Handle Missing Data --------------------------------------------------------
print('--- Missing Values on Daylight---')
print(Plant1_day.isnull().sum())

# --- Drop Rows where sensors had no reading (NaN) ------------------------------
missing_before = len(Plant1_day)
Plant1_day = Plant1_day.dropna(subset=['IRRADIATION', 
                                       'AMBIENT_TEMPERATURE', 
                                       'MODULE_TEMPERATURE'])
print(f'\nRows Dropped: {missing_before - len(Plant1_day)}')
print(f'Rows Remaining: {len(Plant1_day)}')

# --- Compute efficiency ratio ----------------------------------------------------
Plant1_day['AC_POWER'] = Plant1_day['AC_POWER']
Plant1_day['EFFICIENCY_RATIO'] = Plant1_day['AC_POWER'] / Plant1_day['DC_POWER']

# --- Set time index --------------------------------------------------------------
Plant1_day = Plant1_day.sort_values('DATE_TIME')

# --- Plot 1: Efficiency per inverter ---------------------------------------------
plt.figure(figsize=(12, 6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='EFFICIENCY_RATIO')
plt.xticks(rotation=90)
plt.title('Efficiency Ratio per Inverter — Plant 1')
plt.xlabel('Source Key (Inverter)')
plt.ylabel('Efficiency Ratio (AC / DC)')
plt.tight_layout()
#plt.show()

# --- Plot 2: DC power vs irradiation ----------------------------------------------
plt.figure(figsize=(10, 6))
sns.scatterplot(data=Plant1_day, x='IRRADIATION', y='DC_POWER')
plt.title('DC Power vs Irradiation — Plant 1')
plt.xlabel('Irradiation (W/m²)')
plt.ylabel('DC Power (kW)')
plt.tight_layout()
#plt.show()

# --- Plot 3: Fleet Average Efficiency over time -------------------------------------
daily_eff = Plant1_day.groupby(Plant1_day['DATE_TIME'].dt.date)['EFFICIENCY_RATIO'].mean()
plt.figure(figsize=(12,6))
plt.plot(daily_eff.index, daily_eff.values, color='blue')
plt.title('Fleet Average Efficiency Over Time — Plant 1')
plt.xlabel('Date')
plt.ylabel('Mean Efficiency Ratio')
plt.tight_layout()
#plt.show()

# --- Inverter Efficiency Percentile Ranking (Setting for Plot 4) --------------------
inverter_stats = (Plant1_day.groupby('SOURCE_KEY')['EFFICIENCY_RATIO'].
                  agg(['mean', 'median', 'std']).
                  rename(columns={'mean': 'MEAN_EFF', 'median': 'MEDIAN_EFF', 'std': "STD_EFF"}))

inverter_stats['PERCENTILE_RANK'] = (inverter_stats['MEAN_EFF'].rank(pct=True) * 100).round(1)

inverter_stats = inverter_stats.sort_values('MEAN_EFF')
print('\n === Inverter Effeciency Ranking (Worst to Best)')
print(inverter_stats.to_string())

underperformers = inverter_stats[inverter_stats['PERCENTILE_RANK'] <= 25]
print('\n === Underperforming Inverters (Bottom 25th Percentile)')
print(underperformers.to_string())

# --- Plot 4: Inverter ranking bar chart ----------------------------------------------
plt.figure(figsize=(10,6))
colors = ["#E41919" if p <= 25 else 'blue' for p in inverter_stats['PERCENTILE_RANK']]
plt.bar(inverter_stats.index, inverter_stats['MEAN_EFF'], color=colors)
plt.axhline(y=inverter_stats['MEAN_EFF'].quantile(0.25), 
            color='red', 
            linestyle='--',
            linewidth=0.8, 
            label='25th Percentile')
plt.xticks(rotation=90)
plt.title('Mean Efficiency Ratio per Inverter — Plant 1 (red = underperformer)')
plt.xlabel('Source Key (Inverter)')
plt.ylabel('Mean Efficiency Ratio')
plt.ylim(0.975, 0.981)  #   line to make differences visible
plt.tight_layout()
plt.legend()
#plt.show()


# --- Plot 5: Module Temperature vs Efficiency ---------------------------------------
plt.figure(figsize=(12,6))
sns.scatterplot(data=Plant1_day,
                x='MODULE_TEMPERATURE', 
                y='EFFICIENCY_RATIO',
                alpha=0.3)
plt.title('Module Temperature vs Efficiency Ratio — Plant 1')
plt.xlabel('Module Temperature')
plt.ylabel('Efficiency Ratio')
plt.tight_layout()
plt.show()







#===============================================================================================
#===============================================================================================
#===============================================================================================







# --- Feature 1: AC/DC Efficiency Ratio ----------------------------------------------------
Plant1_day['EFFICIENCY_RATIO'] = Plant1_day['AC_POWER'] / Plant1_day['DC_POWER']

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='EFFICIENCY_RATIO')
plt.xticks(rotation=90)
plt.title('AC/DC Efficiency Ratio per Inverter — Plant 1')
plt.xlabel('Inverter')
plt.ylabel('Efficiency Ratio (AC/DC)')
plt.tight_layout()
#plt.show()

# --- Feature 2: Irradiance-Normalized DC Power ---------------------------------------------------
Plant1_day['IRR_NORM_DC'] = Plant1_day['DC_POWER']/Plant1_day['IRRADIATION']

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='IRR_NORM_DC')
plt.xticks(rotation=90)
plt.title('Irradiance-Normalized DC Power per Inverter')
plt.xlabel('Inverter')
plt.ylabel('DC Power / Irradiation (kW / W/m²)')
plt.tight_layout()
#plt.show()

# --- Normalized Power Loss in Temperature Derating --------------------------------------
TEMP_COEFFICIENT = 0.005 #This comes from the fact that power drops ~0.4-0.5% per °C above 25°C (typical for crystalline silicon)

HIGH_IRR_THRESHOLD = Plant1_day['IRRADIATION'].quantile(0.90)

P_RATED = (Plant1_day[Plant1_day['IRRADIATION'] >= HIGH_IRR_THRESHOLD
                     ].groupby('SOURCE_KEY')['DC_POWER'].quantile(0.95))


Plant1_day['P_RATED'] = Plant1_day['SOURCE_KEY'].map(P_RATED)

Plant1_day['EXPECTED_DC'] = Plant1_day['P_RATED'] * (
  1 - TEMP_COEFFICIENT * (Plant1_day['MODULE_TEMPERATURE'] - 25)
  )

Plant1_day['TEMP_DERATING'] = ((Plant1_day['EXPECTED_DC'] - 
                               Plant1_day['DC_POWER']) / Plant1_day['P_RATED']) * 100

# --- Condition derating on irradiation bins to remove weather effect -------------------
Plant1_day['IRR_BIN'] = pd.cut(Plant1_day['IRRADIATION'], bins=10)
Plant1_day['TEMP_DERATING_CONDITIONED'] = Plant1_day.groupby('IRR_BIN')['TEMP_DERATING'].transform(
  lambda x: (x - x.mean()) / x.std())

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='TEMP_DERATING_CONDITIONED')
plt.xticks(rotation=90)
plt.title('Temperature Derating per Inverter (Irradiation-Conditioned)')
plt.xlabel('Inverter')
plt.ylabel('Conditioned Temperature Derating (Z-Score)')
plt.axhline(y=0, color='red', linestyle='--', linewidth=0.8, label='Fleet Mean')
plt.legend()
plt.tight_layout()
#plt.show()


# --- Rolling 1 Hour Average Deviation per Inverter ------------------------------------
Plant1_day = Plant1_day.sort_values(['SOURCE_KEY', 'DATE_TIME'])

Plant1_day['ROLLING_DC_MEAN'] = (
  Plant1_day
  .set_index('DATE_TIME')
  .groupby('SOURCE_KEY')['DC_POWER']
  .transform(lambda x: x.rolling('1h').mean())
  .values
)
Plant1_day['ROLLING_DEVIATION'] = Plant1_day['DC_POWER'] - Plant1_day['ROLLING_DC_MEAN']
Plant1_day = Plant1_day.reset_index()

# --- Full Fleet Overview -----------------

plt.figure(figsize=(12, 6))
for inverter in Plant1_day['SOURCE_KEY'].unique():
    subset = Plant1_day[Plant1_day['SOURCE_KEY'] == inverter]
    plt.plot(subset['DATE_TIME'], subset['ROLLING_DEVIATION'],
             alpha=0.2, linewidth=0.3, color='steelblue')

plt.axhline(y=0, color='red', linestyle='--', linewidth=0.8, label='Zero Deviation')
plt.axhline(y=-2000, color='orange', linestyle='--', linewidth=0.8, label='Warning Threshold (-2000 kW)')
plt.axhline(y=-4000, color='darkred', linestyle='--', linewidth=0.8, label='Critical Threshold (-4000 kW)')
plt.title('Rolling 1-Hour DC Power Deviation — Full Fleet')
plt.xlabel('Date')
plt.ylabel('Deviation from Rolling Mean (kW)')
plt.legend()
plt.tight_layout()

# --- Flagged Inverters ----------------------
flagged = ['sjndEbLyjtCKgGv', 'iCRJl6heRkivqQ3', 
           'McdE0feGgRqW7Ca', 'wCURE6d3bPkepu2', 'bvBOhCH3iADSZry']

colors = ['red', 'orange', 'purple', 'green', 'blue']

plt.figure(figsize=(12, 6))
for inverter, color in zip(flagged, colors):
    subset = Plant1_day[Plant1_day['SOURCE_KEY'] == inverter]
    plt.plot(subset['DATE_TIME'], subset['ROLLING_DEVIATION'],
             alpha=0.7, linewidth=0.5, color=color, label=inverter)

plt.axhline(y=0, color='black', linestyle='--', linewidth=0.8, label='Zero Deviation')
plt.title('Rolling Deviation — Flagged Inverters Only')
plt.xlabel('Date')
plt.ylabel('Deviation from Rolling Mean (kW)')
plt.legend(loc='upper right', fontsize=7)
plt.tight_layout()
#plt.show()


# --- Baseline: Statistical Threshold Method -----------------------------------------------------

#Extracting hour
Plant1_day['HOUR'] = Plant1_day['DATE_TIME'].dt.hour

#Computing Mean and STD per inverter per hour bucket
hourly_stats = (Plant1_day.groupby(['SOURCE_KEY', 'HOUR'])['EFFICIENCY_RATIO']
                .agg(['mean', 'std'])
                .rename(columns={'mean': 'HOUR_MEAN', 'std': 'HOUR_STD'})
                .reset_index()
                )

#Merging back to the main DataFrame
Plant1_day = Plant1_day.merge(hourly_stats, on=['SOURCE_KEY', 'HOUR'], how='left')

Plant1_day['THRESHOLD'] = Plant1_day['HOUR_MEAN'] - 2 * Plant1_day['HOUR_STD']
Plant1_day['ANOMALY_FLAG'] = (Plant1_day['EFFICIENCY_RATIO'] < Plant1_day['THRESHOLD']).astype(int)


#Documenting False Positive Rates
total_readings = len(Plant1_day)
total_flagged = Plant1_day['ANOMALY_FLAG'].sum()
flag_rate = (total_flagged / total_readings) * 100

print(f'Total Reading:    {total_readings}')
print(f'Total Flagged:    {total_flagged}')
print(f'Flag Rate:        {flag_rate:.2f}%')

#Flags per Inverter
inverter_flags = (Plant1_day.groupby('SOURCE_KEY')['ANOMALY_FLAG']
                  .agg(['sum', 'count'])
                  .rename(columns={'sum': 'FLAGS', 'count': 'TOTAL'})
                  )

inverter_flags['FLAG_RATE'] = (inverter_flags['FLAGS'] / inverter_flags['TOTAL'] * 100).round(2)

inverter_flags = inverter_flags.sort_values('FLAG_RATE', ascending=False)

print('\n=== Anomaly Flags per Inverter ===')
print(inverter_flags.to_string())

plt.figure(figsize=(12,6))
sns.barplot(data=inverter_flags.reset_index(), x='SOURCE_KEY', y='FLAG_RATE')
plt.xticks(rotation=90)
plt.axhline(y=flag_rate, color='red', linestyle='--', 
            linewidth=0.8, label=f'Fleet Average ({flag_rate:.2f}%)')
plt.title('Anomaly Flag Rate per Inverter — Baseline Statistical Method')
plt.xlabel('Inverter')
plt.ylabel('Flag Rate (%)')
plt.legend()
plt.tight_layout()
plt.show()





#===============================================================================================
#===============================================================================================
#===============================================================================================


#               MODEL 1
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
import numpy as np

# --- Selecting Features --------------------------------------------------------
features = ['DC_POWER', 'EFFICIENCY_RATIO', 'TEMP_DERATING', 'IRRADIATION']

# --- Dropping rows with NaN (especially TEMP_DERATING from P_RATED) ------------
IF_data = Plant1_day[features + ['DATE_TIME', 'SOURCE_KEY', 'ANOMALY_FLAG']].dropna()

# --- Scale features since Isolation Forest is sensitive to scale ---------------
scaler = StandardScaler()
IF_scaled = scaler.fit_transform(IF_data[features])

print(f'Rows used for Isolation Forest: {len(IF_data)}')
print(f'Features: {features}')

# --- Tune contamination parameter ----------------------------------------------
contamination_values = [0.01, 0.0157, 0.02, 0.05]

for c in contamination_values:
    clf = IsolationForest(contamination=c, random_state=42, n_estimators=100)
    preds = clf.fit_predict(IF_scaled)
    n_anomalies = (preds == -1).sum()
    print(f'Contamination: {c:.4f} -> Anomalies Flagged: {n_anomalies} '
          f'({n_anomalies/len(IF_data) * 100:.2f}%)')

# --- Fit final model -----------------------------------------------------------
clf = IsolationForest(contamination=0.0157, random_state=42, n_estimators=100)
IF_data = IF_data.copy()
IF_data['IF_ANOMALY'] = clf.fit_predict(IF_scaled)
IF_data['IF_ANOMALY'] = (IF_data['IF_ANOMALY'] == -1).astype(int)

print(f'\nTotal IF Anomalies:       {IF_data["IF_ANOMALY"].sum()}')
print(f'Total Baseline Anomalies: {IF_data["ANOMALY_FLAG"].sum()}')

# --- Compare IF vs Baseline (FIXED) -------------------------------------------
IF_data['BOTH_FLAG'] = ((IF_data['IF_ANOMALY'] == 1) &
                         (IF_data['ANOMALY_FLAG'] == 1)).astype(int)

IF_data['IF_ONLY'] = ((IF_data['IF_ANOMALY'] == 1) &
                       (IF_data['ANOMALY_FLAG'] == 0)).astype(int)

# FIXED: separate assignment, correct logic
IF_data['BASELINE_ONLY'] = ((IF_data['IF_ANOMALY'] == 0) &
                              (IF_data['ANOMALY_FLAG'] == 1)).astype(int)

print('\n=== Method Comparison ===')
print(f'Both flagged (agreement):  {IF_data["BOTH_FLAG"].sum()}')
print(f'IF only (baseline missed): {IF_data["IF_ONLY"].sum()}')
print(f'Baseline only (IF missed): {IF_data["BASELINE_ONLY"].sum()}')

# --- Cross-reference with Phase 2 flagged inverters ----------------------------
flagged_inverters = ['sjndEbLyjtCKgGv', 'iCRJl6heRkivqQ3',
                     'bvBOhCH3iADSZry', 'McdE0feGgRqW7Ca',
                     'adLQvlD726eNBSB', 'wCURE6d3bPkepu2']

print('\n=== IF Anomaly Rate per Flagged Inverter ===')
for inverter in flagged_inverters:
    subset = IF_data[IF_data['SOURCE_KEY'] == inverter]
    rate = subset['IF_ANOMALY'].mean() * 100
    baseline_rate = subset['ANOMALY_FLAG'].mean() * 100
    print(f'{inverter}: IF={rate:.2f}%  Baseline={baseline_rate:.2f}%')

# --- Diagnostic Test 1: Run IF without TEMP_DERATING --------------------------
features_clean = ['DC_POWER', 'EFFICIENCY_RATIO', 'IRR_NORM_DC', 'IRRADIATION']
IF_data_clean = Plant1_day[features_clean + ['DATE_TIME', 'SOURCE_KEY', 
                                              'ANOMALY_FLAG']].dropna()
scaler_clean = StandardScaler()
IF_scaled_clean = scaler_clean.fit_transform(IF_data_clean[features_clean])

clf_clean = IsolationForest(contamination=0.0157, random_state=42, n_estimators=100)
IF_data_clean['IF_ANOMALY_CLEAN'] = (clf_clean.fit_predict(IF_scaled_clean) == -1).astype(int)

both_clean = ((IF_data_clean['IF_ANOMALY_CLEAN'] == 1) &
              (IF_data_clean['ANOMALY_FLAG'] == 1)).sum()
print(f'\n=== Diagnostic: IF without TEMP_DERATING ===')
print(f'Agreement rate: {both_clean}/{IF_data_clean["IF_ANOMALY_CLEAN"].sum()} '
      f'= {both_clean/IF_data_clean["IF_ANOMALY_CLEAN"].sum()*100:.1f}%')

# --- Diagnostic Test 2: Check irradiation during anomalies --------------------
print('\n=== Diagnostic: Irradiation during anomalies vs normal ===')
anomaly_irr = IF_data[IF_data['IF_ANOMALY'] == 1]['IRRADIATION'].describe()
normal_irr  = IF_data[IF_data['IF_ANOMALY'] == 0]['IRRADIATION'].describe()
print('Irradiation during anomalies:')
print(anomaly_irr)
print('\nIrradiation during normal readings:')
print(normal_irr)








# Add time context so IF knows peak hours are expected
IF_data['HOUR'] = IF_data['DATE_TIME'].dt.hour
IF_data['HOUR_SIN'] = np.sin(2 * np.pi * IF_data['HOUR'] / 24)
IF_data['HOUR_COS'] = np.cos(2 * np.pi * IF_data['HOUR'] / 24)

features_v2 = ['EFFICIENCY_RATIO', 'IRR_NORM_DC', 
                'TEMP_DERATING', 'ROLLING_DEVIATION',
                'HOUR_SIN', 'HOUR_COS']

IF_data_v2 = Plant1_day.copy()
IF_data_v2['HOUR'] = IF_data_v2['DATE_TIME'].dt.hour
IF_data_v2['HOUR_SIN'] = np.sin(2 * np.pi * IF_data_v2['HOUR'] / 24)
IF_data_v2['HOUR_COS'] = np.cos(2 * np.pi * IF_data_v2['HOUR'] / 24)
IF_data_v2 = IF_data_v2[features_v2 + ['DATE_TIME', 'SOURCE_KEY', 
                                        'ANOMALY_FLAG']].dropna()

scaler_v2 = StandardScaler()
IF_scaled_v2 = scaler_v2.fit_transform(IF_data_v2[features_v2])

clf_v2 = IsolationForest(contamination=0.0157, random_state=42, n_estimators=100)
IF_data_v2['IF_ANOMALY_V2'] = (clf_v2.fit_predict(IF_scaled_v2) == -1).astype(int)

# Check irradiation distribution of new anomalies
print('=== V2 Irradiation during anomalies ===')
v2_anomaly_irr = IF_data_v2[IF_data_v2['IF_ANOMALY_V2'] == 1]['HOUR'].describe()
print(v2_anomaly_irr)

# Check new agreement rate
both_v2 = ((IF_data_v2['IF_ANOMALY_V2'] == 1) & 
            (IF_data_v2['ANOMALY_FLAG'] == 1)).sum()
print(f'\nV2 Agreement rate: {both_v2}/{IF_data_v2["IF_ANOMALY_V2"].sum()} '
      f'= {both_v2/IF_data_v2["IF_ANOMALY_V2"].sum()*100:.1f}%')

# Check flagged inverters
print('\n=== V2 IF Anomaly Rate per Flagged Inverter ===')
for inverter in flagged_inverters:
    subset = IF_data_v2[IF_data_v2['SOURCE_KEY'] == inverter]
    rate = subset['IF_ANOMALY_V2'].mean() * 100
    baseline_rate = subset['ANOMALY_FLAG'].mean() * 100
    print(f'{inverter}: IF_V2={rate:.2f}%  Baseline={baseline_rate:.2f}%')











# --- Plot 1: IF Anomaly Flag Rate per Inverter ---------------------------------
if_inverter_flags = (IF_data.groupby('SOURCE_KEY')['IF_ANOMALY']
                     .agg(['sum', 'count'])
                     .rename(columns={'sum': 'FLAGS', 'count': 'TOTAL'}))
if_inverter_flags['FLAG_RATE'] = (if_inverter_flags['FLAGS'] /
                                   if_inverter_flags['TOTAL'] * 100).round(2)
if_inverter_flags = if_inverter_flags.sort_values('FLAG_RATE', ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(data=if_inverter_flags.reset_index(),
            x='SOURCE_KEY', y='FLAG_RATE')
plt.xticks(rotation=90)
plt.axhline(y=IF_data['IF_ANOMALY'].mean() * 100,
            color='red', linestyle='--', linewidth=0.8, label='Fleet Average')
plt.title('Isolation Forest Anomaly Flag Rate per Inverter')
plt.xlabel('Inverter')
plt.ylabel('Flag Rate (%)')
plt.legend()
plt.tight_layout()
#plt.show()

# --- Plot 2: Anomaly timestamps — 2 columns to fit display --------------------
n = len(flagged_inverters)
fig, axes = plt.subplots(3, 2, figsize=(16, 12))
axes = axes.flatten()

for ax, inverter in zip(axes, flagged_inverters):
    subset = IF_data[IF_data['SOURCE_KEY'] == inverter]
    ax.plot(subset['DATE_TIME'], subset['DC_POWER'],
            color='steelblue', linewidth=0.5, alpha=0.7)
    anomalies = subset[subset['IF_ANOMALY'] == 1]
    ax.scatter(anomalies['DATE_TIME'], anomalies['DC_POWER'],
               color='red', s=15, zorder=5, label='IF Anomaly')
    ax.set_title(f'{inverter}', fontsize=9)
    ax.set_ylabel('DC Power (kW)', fontsize=8)
    ax.tick_params(axis='x', labelsize=7)
    ax.legend(fontsize=7)

plt.suptitle('Isolation Forest Anomalies on DC Power — Flagged Inverters',
             fontsize=12)
plt.tight_layout()
plt.show()