# Context:
# DC_POWER  — DC power generated by inverter in 15-min interval (kW)
# AC_POWER  — AC power output after inversion (kW)
# DAILY_YIELD  — cumulative power generated that day up to that point (kWh)
# TOTAL_YIELD  — total lifetime yield for that inverter (kWh)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Load ----------------------------------------------------------------------
Gen1  = pd.read_csv('Plant_1_Generation_data.csv',     parse_dates=['DATE_TIME'])
Sens1 = pd.read_csv('Plant_1_Weather_Sensor_Data.csv', parse_dates=['DATE_TIME'])

# --- Merge on datetime + plant ID -----------------------------------------------
Plant1_merge = pd.merge(Gen1, Sens1, on=['DATE_TIME', 'PLANT_ID'], how='left')
Plant1_merge = Plant1_merge.drop(columns=['SOURCE_KEY_y'])
Plant1_merge = Plant1_merge.rename(columns={'SOURCE_KEY_x': 'SOURCE_KEY'})

# --- Filter to daylight hours only ----------------------------------------------
Plant1_day = Plant1_merge[
    (Plant1_merge['DC_POWER'] > 0) &
    (Plant1_merge['IRRADIATION'] > 0)
].copy()
del Plant1_merge

# --- Handle Missing Data --------------------------------------------------------
print('--- Missing Values on Daylight---')
print(Plant1_day.isnull().sum())

# --- Drop Rows where sensors had no reading (NaN) ------------------------------
missing_before = len(Plant1_day)
Plant1_day = Plant1_day.dropna(subset=['IRRADIATION', 
                                       'AMBIENT_TEMPERATURE', 
                                       'MODULE_TEMPERATURE'])
print(f'\nRows Dropped: {missing_before - len(Plant1_day)}')
print(f'Rows Remaining: {len(Plant1_day)}')

# --- Compute efficiency ratio ----------------------------------------------------
Plant1_day['AC_POWER'] = Plant1_day['AC_POWER']
Plant1_day['EFFICIENCY_RATIO'] = Plant1_day['AC_POWER'] / Plant1_day['DC_POWER']

# --- Set time index --------------------------------------------------------------
Plant1_day = Plant1_day.sort_values('DATE_TIME')

# --- Plot 1: Efficiency per inverter ---------------------------------------------
plt.figure(figsize=(12, 6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='EFFICIENCY_RATIO')
plt.xticks(rotation=90)
plt.title('Efficiency Ratio per Inverter — Plant 1')
plt.xlabel('Source Key (Inverter)')
plt.ylabel('Efficiency Ratio (AC / DC)')
plt.tight_layout()
#plt.show()

# --- Plot 2: DC power vs irradiation ----------------------------------------------
plt.figure(figsize=(10, 6))
sns.scatterplot(data=Plant1_day, x='IRRADIATION', y='DC_POWER')
plt.title('DC Power vs Irradiation — Plant 1')
plt.xlabel('Irradiation (W/m²)')
plt.ylabel('DC Power (kW)')
plt.tight_layout()
#plt.show()

# --- Plot 3: Fleet Average Efficiency over time -------------------------------------
daily_eff = Plant1_day.groupby(Plant1_day['DATE_TIME'].dt.date)['EFFICIENCY_RATIO'].mean()
plt.figure(figsize=(12,6))
plt.plot(daily_eff.index, daily_eff.values, color='blue')
plt.title('Fleet Average Efficiency Over Time — Plant 1')
plt.xlabel('Date')
plt.ylabel('Mean Efficiency Ratio')
plt.tight_layout()
#plt.show()

# --- Inverter Efficiency Percentile Ranking (Setting for Plot 4) --------------------
inverter_stats = (Plant1_day.groupby('SOURCE_KEY')['EFFICIENCY_RATIO'].
                  agg(['mean', 'median', 'std']).
                  rename(columns={'mean': 'MEAN_EFF', 'median': 'MEDIAN_EFF', 'std': "STD_EFF"}))

inverter_stats['PERCENTILE_RANK'] = (inverter_stats['MEAN_EFF'].rank(pct=True) * 100).round(1)

inverter_stats = inverter_stats.sort_values('MEAN_EFF')
print('\n === Inverter Effeciency Ranking (Worst to Best)')
print(inverter_stats.to_string())

underperformers = inverter_stats[inverter_stats['PERCENTILE_RANK'] <= 25]
print('\n === Underperforming Inverters (Bottom 25th Percentile)')
print(underperformers.to_string())

# --- Plot 4: Inverter ranking bar chart ----------------------------------------------
plt.figure(figsize=(10,6))
colors = ["#E41919" if p <= 25 else 'blue' for p in inverter_stats['PERCENTILE_RANK']]
plt.bar(inverter_stats.index, inverter_stats['MEAN_EFF'], color=colors)
plt.axhline(y=inverter_stats['MEAN_EFF'].quantile(0.25), 
            color='red', 
            linestyle='--',
            linewidth=0.8, 
            label='25th Percentile')
plt.xticks(rotation=90)
plt.title('Mean Efficiency Ratio per Inverter — Plant 1 (red = underperformer)')
plt.xlabel('Source Key (Inverter)')
plt.ylabel('Mean Efficiency Ratio')
plt.ylim(0.975, 0.981)  #   line to make differences visible
plt.tight_layout()
plt.legend()
#plt.show()


# --- Plot 5: Module Temperature vs Efficiency ---------------------------------------
plt.figure(figsize=(12,6))
sns.scatterplot(data=Plant1_day,
                x='MODULE_TEMPERATURE', 
                y='EFFICIENCY_RATIO',
                alpha=0.3)
plt.title('Module Temperature vs Efficiency Ratio — Plant 1')
plt.xlabel('Module Temperature')
plt.ylabel('Efficiency Ratio')
plt.tight_layout()
#plt.show()







#===============================================================================================
#===============================================================================================
#===============================================================================================







# --- Feature 1: AC/DC Efficiency Ratio ----------------------------------------------------
Plant1_day['EFFICIENCY_RATIO'] = Plant1_day['AC_POWER'] / Plant1_day['DC_POWER']

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='EFFICIENCY_RATIO')
plt.xticks(rotation=90)
plt.title('AC/DC Efficiency Ratio per Inverter — Plant 1')
plt.xlabel('Inverter')
plt.ylabel('Efficiency Ratio (AC/DC)')
plt.tight_layout()
#plt.show()

# --- Feature 2: Irradiance-Normalized DC Power ---------------------------------------------------
Plant1_day['IRR_NORM_DC'] = Plant1_day['DC_POWER']/Plant1_day['IRRADIATION']

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='IRR_NORM_DC')
plt.xticks(rotation=90)
plt.title('Irradiance-Normalized DC Power per Inverter')
plt.xlabel('Inverter')
plt.ylabel('DC Power / Irradiation (kW / W/m²)')
plt.tight_layout()
#plt.show()

# --- Normalized Power Loss in Temperature Derating --------------------------------------
TEMP_COEFFICIENT = 0.005 #This comes from the fact that power drops ~0.4-0.5% per °C above 25°C (typical for crystalline silicon)

HIGH_IRR_THRESHOLD = Plant1_day['IRRADIATION'].quantile(0.90)

P_RATED = (Plant1_day[Plant1_day['IRRADIATION'] >= HIGH_IRR_THRESHOLD
                     ].groupby('SOURCE_KEY')['DC_POWER'].quantile(0.95))


Plant1_day['P_RATED'] = Plant1_day['SOURCE_KEY'].map(P_RATED)

Plant1_day['EXPECTED_DC'] = Plant1_day['P_RATED'] * (
  1 - TEMP_COEFFICIENT * (Plant1_day['MODULE_TEMPERATURE'] - 25)
  )

Plant1_day['TEMP_DERATING'] = ((Plant1_day['EXPECTED_DC'] - 
                               Plant1_day['DC_POWER']) / Plant1_day['P_RATED']) * 100

# --- Condition derating on irradiation bins to remove weather effect -------------------
Plant1_day['IRR_BIN'] = pd.cut(Plant1_day['IRRADIATION'], bins=10)
Plant1_day['TEMP_DERATING_CONDITIONED'] = Plant1_day.groupby('IRR_BIN')['TEMP_DERATING'].transform(
  lambda x: (x - x.mean()) / x.std())

plt.figure(figsize=(12,6))
sns.boxplot(data=Plant1_day, x='SOURCE_KEY', y='TEMP_DERATING_CONDITIONED')
plt.xticks(rotation=90)
plt.title('Temperature Derating per Inverter (Irradiation-Conditioned)')
plt.xlabel('Inverter')
plt.ylabel('Conditioned Temperature Derating (Z-Score)')
plt.axhline(y=0, color='red', linestyle='--', linewidth=0.8, label='Fleet Mean')
plt.legend()
plt.tight_layout()
#plt.show()


# --- Rolling 1 Hour Average Deviation per Inverter ------------------------------------
Plant1_day = Plant1_day.sort_values(['SOURCE_KEY', 'DATE_TIME'])

Plant1_day['ROLLING_DC_MEAN'] = (
  Plant1_day
  .set_index('DATE_TIME')
  .groupby('SOURCE_KEY')['DC_POWER']
  .transform(lambda x: x.rolling('1h').mean())
  .values
)
Plant1_day['ROLLING_DEVIATION'] = Plant1_day['DC_POWER'] - Plant1_day['ROLLING_DC_MEAN']
Plant1_day = Plant1_day.reset_index()

# --- Full Fleet Overview -----------------

plt.figure(figsize=(12, 6))
for inverter in Plant1_day['SOURCE_KEY'].unique():
    subset = Plant1_day[Plant1_day['SOURCE_KEY'] == inverter]
    plt.plot(subset['DATE_TIME'], subset['ROLLING_DEVIATION'],
             alpha=0.2, linewidth=0.3, color='steelblue')

plt.axhline(y=0, color='red', linestyle='--', linewidth=0.8, label='Zero Deviation')
plt.axhline(y=-2000, color='orange', linestyle='--', linewidth=0.8, label='Warning Threshold (-2000 kW)')
plt.axhline(y=-4000, color='darkred', linestyle='--', linewidth=0.8, label='Critical Threshold (-4000 kW)')
plt.title('Rolling 1-Hour DC Power Deviation — Full Fleet')
plt.xlabel('Date')
plt.ylabel('Deviation from Rolling Mean (kW)')
plt.legend()
plt.tight_layout()

# --- Flagged Inverters ----------------------
flagged = ['sjndEbLyjtCKgGv', 'iCRJl6heRkivqQ3', 
           'McdE0feGgRqW7Ca', 'wCURE6d3bPkepu2', 'bvBOhCH3iADSZry']

colors = ['red', 'orange', 'purple', 'green', 'blue']

plt.figure(figsize=(12, 6))
for inverter, color in zip(flagged, colors):
    subset = Plant1_day[Plant1_day['SOURCE_KEY'] == inverter]
    plt.plot(subset['DATE_TIME'], subset['ROLLING_DEVIATION'],
             alpha=0.7, linewidth=0.5, color=color, label=inverter)

plt.axhline(y=0, color='black', linestyle='--', linewidth=0.8, label='Zero Deviation')
plt.title('Rolling Deviation — Flagged Inverters Only')
plt.xlabel('Date')
plt.ylabel('Deviation from Rolling Mean (kW)')
plt.legend(loc='upper right', fontsize=7)
plt.tight_layout()
plt.show()