#A little context with the data
#DC_POWER Amount of DC power generated by the inverter (source_key) in this 15 minute interval (kW)
#AC_POWER Amount of AC power generated by the inverter (source_key) in this 15 minute interval (kw)
#DAILY_YIELD Daily yield is a cumulative sum of power generated on that day, till that point in time.
#TOTAL_YIELD This is the total yield for the inverter till that point in time.

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


Plant_1_Generation = pd.read_csv('Plant_1_Generation_data.csv')
Plant_1_Weather = pd.read_csv('Plant_1_Weather_Sensor_Data.csv')

#Merging the two data
Plant1_merge = pd.merge(Plant_1_Generation)


#Plotting the DC inverter data
plt.figure(figsize=(12,6))
sns.barplot(Plant_1_Generation['DC_POWER'], Plant_1_Weather['IRRADIATION'])
plt.show()